(DEFUN prime (n)
	(if (<= n 1)
		(return-from prime nil)
 	)
 	(let ((i 2))
  		(loop
			(when (> (* i i) n) (return T))
   			(if (= (mod n i) 0)
    				(return  nil)
   			)
   			(setq i (+ i 1))
  		)
 	)
)

(format t "~a~&" (prime 2))
(format t "~a~&" (prime 239))
(format t "~a~&" (prime 999))
(format t "~a~&" (prime 17))
